<a href="https://colab.research.google.com/github/Gokulraj1234/DATASCIENCE-LAB/blob/main/Gokul_Raj_CO_1_Matrix_Operations_%26_Creating_a_dataframe_StudentCopy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Matrix Operations

#### Matrices

In [ ]:
# Create a matrix using the 'matrix()' function of the 'numpy' module.
import numpy as np
x=np.matrix('1 2 3;4 5 6;7 8 9')
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Convert a nested Python list into a matrix using the 'matrix()' function of the 'numpy' module.
y=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Matrix Multiplication



$$\begin{bmatrix} 8 & 7 \\ 3	& -5	\\\end{bmatrix} \begin{bmatrix} 3 \\ 2 \\\end{bmatrix}$$

To multiply two matrices, you have to use the `matmul()` function of the `numpy` module. It takes two matrices to be multiplied as inputs and returns a new matrix.

In [ ]:
# Multiplication of the above two matrices.
x=np.matrix('8 7;3 -5')
b=np.matrix('3;2')
e=np.matmul(x,b)
print(e)

[[38]
 [-1]]


**Note:** The number of columns in the first matrix should be the same as the number of rows in the second matrix. Otherwise, you will get `ValueError`

####  Identity Matrix

In [ ]:
# Create an identity matrix of the dimension 5 and of 'int' type.
id_mat=np.identity(5,dtype=int)
print(id_mat)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Now let's multiply a square matrix with an identity matrix of the same dimension (say 3).

In [ ]:
# Multiply a square matrix with an identity matrix of the same dimension.
x=np.matrix('1 2 3;4 5 6;7 8 9')
y=np.identity(3,dtype=int)
e=np.matmul(x,y)
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


----

####  Multiplicative Inverse of a Matrix^


Eg. let $A$ be a matrix of dimension $3$

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

Then its inverse is

$$A^{-1} = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix}$$

Both $A$ and $A^{-1}$ have the same dimension.

If you multiply the matrix $A$ with its inverse, you should get the identity matrix of dimension $3$.

$$A^{-1} A = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix} \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 7 \times 1 - 3 \times 1 -3 \times 1 &7 \times 3 - 3 \times 4 -3 \times 3 & 7 \times 3 - 3 \times 3 - 3 \times 4 \\ -1 \times 1 + 1 \times 1 + 0 \times 1 & -1 \times 3 + 1 \times 4 + 0 \times 3 & -1 \times 3 + 1 \times 3 + 0 \times 4 \\ -1 \times 1 + 0 \times 1 + 1 \times 1 & -1 \times 3 + 0 \times 4 + 1 \times 3 & -1 \times 3 + 0 \times 3 + 1 \times 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\\end{bmatrix}$$


In [ ]:
#Multiply the above matrix with its inverse.
x=np.matrix('1 3 3;1 4 3;1 3 4')
n=np.linalg.inv(x)
e=np.matmul(x,n)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Determinant of a Matrix^^


$$X = \begin{bmatrix} 8 & 7 \\ 3	& -5 \\\end{bmatrix}$$

 To calculate the determinant value of a square matrix, use the `linalg.det()` function of the `numpy` module.

**Syntax:** `np.linalg.det(a)`

where `a` is some square matrix.

In [ ]:
# Calculate the determinant of the matrix X.
x=np.matrix('8 7;3 -5')
det_x=np.linalg.det(x)
print(det_x)

-60.99999999999995


Let's calculate the determinant of the matrix

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

using Python.

In [ ]:
#Calculate the determinant of the above matrix A.
x=np.matrix('1 3 3;1 4 3;1 3 4')
det_x=np.linalg.det(x)
print(det_x)

1.0


In [ ]:
# Calculate the inverse of the above matrix A.
x=np.matrix('1 3 3;1 4 3;1 3 4')
n=np.linalg.inv(x)
print(n)

[[ 7. -3. -3.]
 [-1.  1.  0.]
 [-1.  0.  1.]]


In [ ]:
#Create a dictionary to store weatherdata and convert it to a dtaframe
import pandas as pd
weatherdata={'Day':['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
              'City':['Kollam','Muvattupuzha','Kottayam','Ernakulam','Kochi','Kadavantra','Kakkanad'],
              'Temparature':[20,30,40,50,80,75,65],
              'Windspeed':[30,50,40,80,35,20,25]}
# Display the first five rows of dataframe
df=pd.DataFrame(weatherdata)
df.head()



Day          City  Temparature  Windspeed
0     Monday        Kollam           20         30
1    Tuesday  Muvattupuzha           30         50
2  Wednesday      Kottayam           40         40
3   Thursday     Ernakulam           50         80
4     Friday         Kochi           80         35

In [ ]:
#Display the last five rows of dataframe
df.tail()

Day        City  Temparature  Windspeed
2  Wednesday    Kottayam           40         40
3   Thursday   Ernakulam           50         80
4     Friday       Kochi           80         35
5   Saturday  Kadavantra           75         20
6     Sunday    Kakkanad           65         25